; <?php die(); ?>

[general]
host = "localhost"
user = "root"
pwd = ""
name = "guilddkp"
pre = "dkp_"

[define]
T_USER = "dkp_user"
T_SESSIONS = "dkp_sessions"
T_RANKS_RIGHTS = "dkp_ranks_rights"
T_RANKS = "dkp_ranks"
T_NEWS = "dkp_news"
T_BOSS = "dkp_boss"
T_BA = "dkp_boss_attendees"
T_CHAR = "dkp_char"
T_DKP = "dkp_dkp"
T_POST = "dkp_post"
T_TOPIC = "dkp_topic"
T_FORUM = "dkp_forum"
T_LOOT = "dkp_loot"
T_RAID = "dkp_raid"
T_RT = "dkp_raid_type"
T_RA = "dkp_raid_attendees"
;T_LOGS = "dkp_logs"
T_ITEMS = "wow_items"
T_SPELLS = "wow_spells"
T_NPC = "wow_npc"
T_QUESTS = "wow_quests"
T_COMMENTS = "dkp_comments"
